### ISSUE TITLE
One step closer to our bootcamp

### ISSUE THREAD

**Issue by mrivas616** [mrivas616/FITOReactJSBootcamp#3]
After reviewing many applications for our bootcamp, we have chosen you to be part of this experience. Please navigate to the code section of this repo and proceed to read further instructions in the README.md file.

@daniem11 , @ashikabi , @miltondl96 , @menendezisma , @fvHer , @eduardorr21 , @felixcarpio , @jonathanB21 , @kernel503 , @stefanymenjiivar , @gomezdev97  , @sanortiz , @katymorales , @marlon427 , @DamarisVY , @jemestica , @pipolorencia , @theedu007 , @Evillam97 , @Beck2301 , @Marcomps , @Nrycord , @EddyRC , @kikeAKAdelta , @lilygrande , @CoreasMarlon , @sigfridos , @irvinparedes23 , @oguev , @EduardoSorto23 , @luisguztav20 , @MikeHub743 , @JRSV1809 , @websterpineda , @argd14 , @ClauzdyzPineda , @SaraG65 , @marvinomar , @marlon-lopez , @mc11057 , @snaven10 , @irvindeveloper , @JesusZelayaG , @AChapeton , @cr15t14n , @fendergx , @caceres08 , @celinaViscarra , @hijpax , @LisJorge

EDIT: You can submit your video either in Spanish or English, don't hesitate to show us your English skills though 💯 

Thank you all!

**Comment by mrivas616** [comment]
@crismbb , @rguevarasv , @Nathaa , @PaoAguilar , @Will667 , @LiseoLopez , @claudia211292 , @Jzee030817 , @diegogarcia10 , @ElvisGmz , @CryptoJss , @rdv9 , @And0896 , @Vale027 , @MarlonMazariego , @MarvinVas11 , @Jeff-Alvares , @RJaco1 , @Doris08 , @Frgmoran , @josueffxi , @Franklin2555 , @erickmendezz , @danielwilfredo , @Henry-Cardona , @Closterman , @jcesar020 , @hftamayo , @Stronk1 , @RaulTrigueros , @david98joe , @DrDaxter , @jrg96 , @SalvadorPerz , @luigichevez19 , @renealas , @mabigailg96 , @MarioV32 , @alejandroTrejo2019 , @NelNav1222 , @Ceschom10

**Comment by EddyRC** [comment]
Gracias por la oportunidad!
Solo tengo una duda, la descripcion del video tiene que ser en ingles?

**Comment by mrivas616** [comment]
> Gracias por la oportunidad! Solo tengo una duda, la descripcion del video tiene que ser en ingles? El mar, 1 dic 2020 a las 11:00

Puede ser ya sea en ingles o español 👍

**Comment by irvindeveloper** [comment]
Gracias por la oportunidad

**Comment by erickmendezz** [comment]
Hello, this is a great new. Thanks for the opportunity. is there a limit time for send video?

**Comment by mrivas616** [comment]
> 
> 
> Hello, this is a great new. Thanks for the opportunity. is there a limit time for send video?

You are welcome 👍 we'll be expecting your video submissions until midnight Sunday Dec 6th.

**Comment by Stronk1** [comment]
Muy buenas tardes, le escribo de manera tardia, digame que necesita cuales
serian los requerimientos
